### ISSUE TITLE
Jak zmienić walutę w przykładzie TransactionApi -> CardGate

### ISSUE THREAD

**Issue by marcinulezalka** [tpay-com/tpay-openapi-php#10]
W `Examples\TransactionsApi\CardGate.php` 

dodając do $request walutę 

'currency' => 'EUR',

generuje błąd

```
Fatal error: Uncaught InvalidArgumentException: Field currency is not supported in vendor/tpay-com/tpay-openapi-php/Model/Objects/Objects.php:62 Stack trace: #0 vendor/tpay-com/tpay-openapi-php/Manager/Manager.php(20): tpaySDK\Model\Objects\Objects->setObjectValues(Object(tpaySDK\Model\Objects\RequestBody\Transaction), Array) #1 vendor/tpay-com/tpay-openapi-php/Api/ApiAction.php(49): tpaySDK\Manager\Manager->setFields(Array) #2 vendor/tpay-com/tpay-openapi-php/Api/Transactions/TransactionsApi.php(42): tpaySDK\Api\ApiAction->run('POST', '/transactions', Array, Object(tpaySDK\Model\Objects\RequestBody\Transaction)) #3 vendor/tpay-com/tpay-openapi-php/Examples/TransactionsApi/CardGate.php(147): tpaySDK\Api\Transactions\Transa in vendor/tpay-com/tpay-openapi-php/Model/Objects/Objects.php on line 62
```

**Comment by BanczerowskiM** [comment]
Cześć @marcinulezalka,
obecnie integracja z naszym systemem poprzez Open API nie umożliwia wykonywania transakcji w innej walucie niż PLN, stad komunikat o błędzie, kiedy dodajesz parametr 'currency'. 

Jeśli potrzebujesz przyjmować środki innej walucie, skorzystaj z integracji Origin API, gotowa biblioteka jest dostępna pod tym linkiem: https://github.com/tpay-com/tpay-php a dokumentacja do niej tu: https://docs.tpay.com/#!/Tpay/Cards_API_introduction. 

Przyjmowanie transakcji w obcej walucie jest możliwe jedynie za pośrednictwem kart płatniczych.
