### ISSUE TITLE
Gpay - Uncaught InvalidArgumentException: Field googlePayPaymentData is not supported

### ISSUE THREAD

**Issue by marcinulezalka** [tpay-com/tpay-openapi-php#12]
Wywołanie gPay zgodnie z 

[https://support.tpay.com/en/merchant/google-pay-tm-on-site](https://support.tpay.com/en/merchant/google-pay-tm-on-site)

zwraca

```
Fatal error: Uncaught InvalidArgumentException: Field googlePayPaymentData is not supported in vendor/tpay-com/tpay-openapi-php/Model/Objects/Objects.php:85 Stack trace: #0 vendor/tpay-com/tpay-openapi-php/Model/Objects/Objects.php(49): tpaySDK\Model\Objects\Objects->setObjectsInArray(Object(tpaySDK\Model\Objects\RequestBody\Transaction), Array, 'pay') #1 vendor/tpay-com/tpay-openapi-php/Manager/Manager.php(20): tpaySDK\Model\Objects\Objects->setObjectValues(Object(tpaySDK\Model\Objects\RequestBody\Transaction), Array) #2 vendor/tpay-com/tpay-openapi-php/Api/ApiAction.php(49): tpaySDK\Manager\Manager->setFields(Array) #3 vendor/tpay-com/tpay-openapi-php/Api/Transactions/TransactionsApi.php(42): tpaySDK\Api\ApiAction->run(' in vendor/tpay-com/tpay-openapi-php/Model/Objects/Objects.php on line 85
```

**Comment by kkotwica** [comment]
@marcinulezalka zmiana zawierająca obsługę googlePayPaymentData w https://github.com/tpay-com/tpay-openapi-php/releases/tag/1.2.0
